### ISSUE TITLE
More complex filters

### ISSUE THREAD

**Issue by goldshtn** [goldshtn/etrace#7]
Currently, filters are any-of, and they are very simple. Some ideas for extending filters:

* All-of filters, e.g. `--where "ProcessName=w3wp && PayloadField=223"`
* Filters with additional operators, e.g. `--where PayloadField>223`

**Comment by Pavel-Durov** [comment]
I think this issue should be closed

>Issue #7 : More complex filters #8

PR is merged

**Comment by goldshtn** [comment]
Yes. In the future, if you add "resolves #NNN" or "fixes #NNN" to the PR description, it will auto-close the issue when it's merged.

**Comment by Pavel-Durov** [comment]
Alright, will do. Thanks
